apiVersion: v1
kind: Service
metadata:
  name: helloweb
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: sample-lb
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: hello
    tier: web
  type: LoadBalancer
