config:
  target: 'ws://socketserver:8081/someTest'
  phases:
    - duration: 30
      arrivalRate: 10
  ws:
    maxRedirects: 25

scenarios:
  - engine: ws
    name: Echo a string
    flow:
      - send: 'Hello from Artillery'
