apiVersion: v1
kind: Service
metadata:
  name: whatsbackend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: whatsbackend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsbackend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whatsbackend
  template:
    metadata:
      labels:
        app: whatsbackend
    spec:
      containers:
      - name: whatsbackend
        image: obarker94/whatsbackend:rc-123
        ports:
        - containerPort: 80
        env:  # Add this section to set environment variables
        - name: OTEL_COLLECTOR_ADDRESS
          value: "http://app-opentelemetry-collector.default.svc.cluster.local:4318"
