global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets: ['otel_collector:8889']
      - targets: ['otel-collector:8888']
    metric_relabel_configs:
      - source_labels: [span_name]
        target_label: span_name
