receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: '0.0.0.0:14278'

  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:

  prometheus:
    endpoint: '0.0.0.0:8889'

  otlp:
    endpoint: 'jaeger:4317'
    tls:
      insecure: true

connectors:
  spanmetrics:

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch, spanmetrics]
      exporters: [spanmetrics, otlp]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [debug, prometheus]
