name: deployment

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set Docker image name
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME}}/${{ github.event.repository.name}}"
        IMAGE_TAG="${{ github.run_id }}"
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG
      env:
        DOCKER_CLI_ACI: 1

    - name: Clone repository
      run: |
        git config --global user.name ${{ secrets.GITHUB_USERNAME}}
        git config --global user.email ${{ secrets.GITHUB_EMAIL}}
        git clone https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
    
    - name: List all files in kubernetes sub-folder
      run: |
        ls ./kubernetes



