name: deployment

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set Docker image name
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME}}/${{ github.event.repository.name}}"
        IMAGE_TAG="${{ github.run_id }}"
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG
      env:
        DOCKER_CLI_ACI: 1

  tag-and-commit:
    needs: docker
    runs-on: ubuntu-latest
    steps:

    - name: Clone repository
      run: |
        git config --global user.name "${{ secrets.GH_USERNAME }}"
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git clone https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
        ls
    
    - name: List all files in kubernetes sub-folder
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME}}/${{ github.event.repository.name}}"
        echo $IMAGE_NAME
        IMAGE_TAG="${{ github.run_id }}"

        awk -v image_name="$IMAGE_NAME" -v tag="$IMAGE_TAG" '{
          if ($0 ~ "image: " image_name) {
            sub("image: " image_name ".*", "image: " image_name ":" tag)
          }
          print $0
        }' ./${{ github.event.repository.name }}/kubernetes/deployment.yaml > temp.yaml && mv temp.yaml ./${{ github.event.repository.name }}/kubernetes/deployment.yaml

    - name: Commit the ammended repo
      run: |

       if [ "$GITHUB_ACTOR" = "github-actions[bot]" ]; then
          echo "The commit was made by GitHub Actions bot. Skipping the workflow."
          exit 78 # Skip the workflow with a neutral status
        fi

        cd ./${{ github.event.repository.name }}
        git commit -am "Build Successful - ${{ github.run_id }}"
        git push

    - name: Print the file contents
      run: |
        cat ./${{ github.event.repository.name }}/kubernetes/deployment.yaml



